name: anymex
description: "An Anilist Client"
publish_to: "GitHub"
version: 2.9.7+13

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  algorithmic: ^0.0.11
  blur: ^4.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  checkmark: ^0.0.2+1
  crypto: any
  dart_eval: ^0.7.10
  device_info_plus: ^11.2.2
  dio: ^5.8.0+1
  dynamic_color: ^1.7.0
  encrypt: ^5.0.3
  expandable_page_view: ^1.0.17
  extended_image: ^9.1.0
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^18.0.1
  flutter_markdown: ^0.7.6
  flutter_native_splash: ^2.4.4
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main
  flutter_riverpod: ^2.6.1
  flutter_rust_bridge: ^2.7.0
  flutter_web_auth_2: ^4.0.2
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  grouped_list: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: any
  http: ^1.2.2
  http_interceptor: ^2.0.0
  hugeicons: ^0.0.7
  iconly: ^1.0.1
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  install_plugin: ^2.1.0
  intl: ^0.20.1
  isar: ^3.1.0+1
  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  js_packer: ^0.0.5
  json_annotation: ^4.9.0
  json_path: ^0.7.4
  kenburns_nullsafety: ^1.0.1
  manga_page_view: ^1.0.5
  
  # repo => https://github.com/media-kit/media-kit
  media_kit: ^1.2.0
  media_kit_libs_video: ^1.0.6
  media_kit_video: ^1.2.5

  outlined_text: ^1.0.1
  package_info_plus: any
  path: any
  path_provider: any
  permission_handler: ^11.3.1
  provider: ^6.1.2
  pseudom: ^1.0.1
  riverpod_annotation: ^2.6.1
  screen_brightness: ^0.2.2+1
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  super_sliver_list: ^0.4.1
  uni_links: ^0.5.1
  uni_links_desktop: any
  url_launcher: any
  volume_controller: ^2.0.8
  window_manager: ^0.4.3
  xpath_selector_html_parser: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.11
  change_app_package_name: ^1.4.0
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  inno_bundle: ^0.7.4

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 256
  macos:
    generate: false
    image_path: "assets/images/logo.png"

flutter_native_splash:
  fullscreen: true
  color: "#000000"
  image: assets/images/logo.png
  android_12:
    color: "#000000"
    image: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf

inno_bundle:
  id: 8fbd47cb-d6e1-5343-a9f6-61661647c94c
  publisher: Ryan Yuuki
  name: AnymeX
  version: 2.9.7
  admin: auto
  installer_icon: ./anymex.ico
